// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	"rainbot/biz/config"
	"rainbot/biz/handler"
)

func main() {
	config.InstallBaseConfig()
	h := server.Default()
	handler.BindService()
	register(h)
	h.Spin()
}
